server:
  port: 9988
spring:
  application:
    name: zuul-gateway-dev
zuul:
  routes:
    plat.serviceId: aigou-plat-dev #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
    product.serviceId: aigou-product-dev
    product.path: /product/**
    common.serviceId: aigou-common-dev
    common.path: /common/**
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
